@startuml

Dispacher --> JobManagerRunner_JobMaster: jobManagerRunnerFactory.createJobManagerRunner

JobManagerRunner_JobMaster --> SchedulerNG: SlotPoolServiceSchedulerFactory.createScheduler

@enduml